### ISSUE TITLE
Update golden files with strain URIs

### ISSUE THREAD

**Issue by jakebeal** [SD2E/experimental-intent-parser#207] opened 2020-06-22 19:41 UTC
Following #205, update golden files to have URIs for strains.  Keep this on a branch for @tramyn to test against in developing #206.  Both #206 and this issue should have for their merges run at the same time.

**Comment by tramyn** [comment] 2020-08-14 20:32
I have updated the golden files for IP testing. 35/37 are failing this type of testing because strains no longer match the golden files expected output. I will need @mwes to update these golden files with new results in order to get these test cases passing again. 
@mwes let me know when this is ready to reassign to me so I can resolve IP's current state with golden file testing.

**Comment by mwes** [comment] 2020-08-17 12:28
Thanks @tramyn I'll work on this today

**Comment by mwes** [comment] 2020-08-18 16:58
FYI, I am still working on this. 

https://github.com/SD2E/experimental-intent-parser/issues/205 will require many previously valid ERs to be manually updated so that they can be run through the IP

I will then update the parsing we provide to XPlan from the new IP/SR strain output so that we don't break the existing XPlan integration when this milestone is released.

**Comment by tramyn** [comment] 2020-08-18 20:26
@mwes I'm going to leave #205 and #207 as the last 2 issues accounted for 2.8 release. Once these two issues are resolved, we are going to package this up and push to production. The remaining issues for #212 and #218 will be move to 2.9 milestone release.  Let me know if you have concerns with this decision.

**Comment by mwes** [comment] 2020-08-18 21:03
That sounds fine @tramyn

**Comment by mwes** [comment] 2020-08-19 21:08
@tramyn this is more labor intensive than I thought. I have a way forward, however. See below.

Each strain entry in the ER has to be manually re-linked so that it points to the correct lab id and links to the correct URI. This is, unfortunately, not a mindless process as the ERs to date have been inconsistent: some use common names, some use URIs, etc. hence the idea around this request. To resolve it I have to look through the ER and re-map to the correct values. Most ERs have an average of ~50+ strains; so this is taking me about ~15-20 minutes to do input and check, assuming I don't make any mistakes.

We have a large number of previously run ERs that are out of date (~47 processed and checked in). This will take a long time to do and for the purposes fo the program, those earlier ERs have a very low likelihood of being re-processed through IP. Even if they are, the strain information we're gaining is minimal. 

My suggested path forward is the following:

Update the ERs for the two latest Strateos ERs we processed in July and June:
1.0 Growth Curves: https://docs.google.com/document/d/1fFcxyJyheMrzSsVoSsO6v7qHJKFf_0heIFtqEur02cg/edit
1.0 Time Series Round 1: https://docs.google.com/document/d/1Mba6kqDila4W32Z46NEqXZFx868A3O36I9GIVOvMQ70/edit#

I've confirmed that the strain parsing/generation works for these two, and will update the structured request documents. Nothing else in the diff changed outside of the strains, so from my perspective the generation is working and consistent. Use these as a new nucleus for golden file checks.

At the same time, I've updated the relevant code that interacts with the IP output, and made it backwards and forwards compatible with both formats. If we use a previous IP-generated output, it will work, and same for the new version going forward. This should allow you to do the release without breaking the existing XPlan integration.

For older ERs: If we need to re-process these through the IP, we'll need to manually update the strains as needed. We can do this on a case-by-case basis. 

Thoughts?

I am posting an MR for all of the above shortly, and will link it here when reviewed and merged.

**Comment by tramyn** [comment] 2020-08-19 21:24
@mwes sounds like a good solution. If we get to a point where you no longer want to update your generated ER files so that I can treat them as golden files for IP's testing, then please let me know so I can update IP tests to reflect that change. Otherwise, let me know when the generated files are ready for me to test.

**Comment by mwes** [comment] 2020-08-19 21:44
Sure. https://gitlab.sd2e.org/sd2program/cp-request/merge_requests/500 is pending.

The new golden files to test against will be: 
https://gitlab.sd2e.org/sd2program/cp-request/blob/1d134ee3a0921299a4b998d48f25ecee54f6b7dc/input/structured_requests/YeastSTATES%201.0%20Growth%20Curves%20Request.json
https://gitlab.sd2e.org/sd2program/cp-request/blob/1d134ee3a0921299a4b998d48f25ecee54f6b7dc/input/structured_requests/YeastSTATES%201.0%20Time%20Series%20Round%201.json

**Comment by mwes** [comment] 2020-08-20 13:22
@tramyn this has been review and merged through; once golden file testing passes for those two ERs, we should be good to go for milestone 2.8

**Comment by tramyn** [comment] 2020-08-20 14:03
@mwes Thank you Mark. I'll work on this now.

**Closed** 2020-08-20 21:02 UTC
